config/routes.rb
Rails.application.routes.draw do
  devise_for :applicantusers
  devise_for :headhunterusers

  root to: 'home#index'

  resources :jobs do
    get 'search', on: :collection
  end

  resources :applicants

  get '/meu-perfil', to: 'applicants#profile'
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  validates :name, :social_name, :birthdate, :education, :description, :location, :avatar, presence: true

  has_one_attached :avatar
  belongs_to :applicantuser

  accepts_nested_attributes_for(allow_destroy: true)

  def thumbnail
    return self.avatar.variant(resize: '250x250!').processed
  end
end

app/models/applicantuser.rb
class Applicantuser < ApplicationRecord
  has_one :applicant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/headhunteruser.rb
class Headhunteruser < ApplicationRecord
  has_many :job
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true

  belongs_to :headhunteruser

  accepts_nested_attributes_for(allow_destroy: true)

  def closed_for_application
    return if Job.application_deadline == Date.today
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update]

  def index
    @applicants = Applicant.all
  end
  
  def profile
    @profile = current_applicantuser
  end

  def show    
    @applicant = Applicant.find(params[:id])
  end

  def new
    @applicant = Applicant.new    
  end

  def create
    @applicant = current_applicantuser.build_applicant(applicant_params)

    if @applicant.save
      redirect_to @applicant
    else
      render :new      
    end
  end

  def edit
  end

  def update
    if @applicant.update(applicant_params)
      redirect_to @applicant
    else
      render 'edit'
    end  
  end

  private

  def set_applicant
    @applicant = Applicant.find(params[:id])
  end

  def applicant_params
    params.require(:applicant).permit(:name, :social_name, :birthdate, :education, :description, :location, :avatar)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_headhunteruser.job.build(job_params)

    if @job.save
      redirect_to @job
    else
      render :new #O render, ao contrário do redirect, só chama a mesma view nao perdendo o que o user já escreveu.
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def destroy
    @job.delete
    redirect_to jobs_path
  end

  def search
    @search_query = params[:query]
    @jobs = Job.where("title LIKE ?", "%#{@search_query}%")
               .or(Job.where("description LIKE ?", "%#{@search_query}%"))
    render :index
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :skills, :salary, :application_deadline, :location, :level)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applicants/_form.html.erb
<% if @applicant.errors.full_messages.any? %>
  <p> Não foi possível salvar, verifique os erros abaixo: </p>
  <ul>
    <% @applicant.errors.full_messages.each do |a|%>
      <li><%= a %></li>
    <%end%>
  </ul>
<% end %>

<%= form_for(@applicant) do |a| %>

    <%= a.label :name, 'Nome Completo' %>
    <%= a.text_field(:name) %>

    <%= a.label :social_name, 'Nome Social' %>
    <%= a.text_field(:social_name) %>

    <%= a.label :birthdate, 'Data de Nascimento' %>
    <%= a.text_field(:birthdate) %>

    <%= a.label :education, 'Formação' %>
    <%= a.text_field(:education) %>

    <%= a.label :description, 'Descrição' %>
    <%= a.text_field(:description) %>

    <%= a.label :location, 'Localização'%>
    <%= a.text_field(:location) %>

    <%= a.label :avatar, 'Foto de Perfil' %>
    <%= a.file_field(:avatar) %>

    <%= a.submit('Enviar') %>
<% end %>

app/views/applicants/edit.html.erb
<h1> Editar Vaga </h1>

<%= render 'form'%>

app/views/applicants/index.html.erb
<h1> Área do Candidato </h1> 

<% if @applicants.empty? %>
  <p> Perfil não cadastrado </p>
  <%= link_to 'Cadastrar Perfil', new_applicant_path %>
<% else %>
  <%= link_to 'Meu Perfil', meu_perfil_path %>
  <%= link_to 'Ver Vagas', jobs_path %>
<% end %>

app/views/applicants/new.html.erb
<h1> Novo Perfil </h1>

<%= render 'form'%>

app/views/applicants/profile.html.erb
<h1> Perfil do Candidato </h1> 

<h1><%= "#{@profile.applicant.social_name} Perfil"%></h1> 

<%= image_tag @profile.applicant.thumbnail %>
<%= @profile.applicant.name %>
<%= @profile.applicant.education %>
<%= @profile.applicant.description %>
<%= I18n.l @profile.applicant.birthdate, format: :custom %>
<%= @profile.applicant.location %>

<%= link_to 'Editar', edit_applicant_path(@profile.applicant.id) %>
<%= link_to 'Voltar', meu_perfil_path %>

app/views/applicants/show.html.erb
<h1><%= "#{@applicant.social_name} Perfil"%></h1> 

<%= image_tag @applicant.thumbnail %>
<%= @applicant.name %>
<%= @applicant.education %>
<%= @applicant.description %>
<%= I18n.l @applicant.birthdate, format: :custom %>
<%= @applicant.location %>

<%= link_to 'Editar', edit_applicant_path(@applicant.id) %>
<%= link_to 'Voltar', applicants_path %>

app/views/home/index.html.erb
<h1> HeadHunters </h1>

<h1> Bem vindo ao sistema de gestão de empregos</h1>

app/views/jobs/_form.html.erb
<% if @job.errors.full_messages.any? %>
  <p> Não foi possível salvar, verifique os erros abaixo: </p>
  <ul>
    <% @job.errors.full_messages.each do |j|%>
      <li><%= j %></li>
    <%end%>
  </ul>
<% end %>

<%= form_for(@job) do |j| %>

    <%= j.label :title %>
    <%= j.text_field(:title) %>

    <%= j.label :description %>
    <%= j.text_field(:description) %>

    <%= j.label :level %>
    <%= j.text_field(:level) %>

    <%= j.label :skills %>
    <%= j.text_field(:skills) %>

    <%= j.label :salary %>
    <%= j.text_field(:salary) %>

    <%= j.label :application_deadline%>
    <%= j.text_field(:application_deadline) %>

    <%= j.label :location %>
    <%= j.text_field(:location) %>

    <%= j.submit('Enviar') %>
<% end %>

app/views/jobs/index.html.erb
<h1> Vagas </h1>

<h2> Resultado da busca por: <%= @search_query %></h2>
<% if @jobs.count == 0 %>
  <%= t :job, count: 0%>
<% else %>  
  <p><%= @jobs.count %> Vagas Encontradas</p>
<% end %>  
<%= form_with url:search_jobs_path, local: true, method: :get do |f|%>
  <%= f.label :query, 'Busca' %>
  <%= f.search_field :query %>
  <%= f.submit 'Buscar' %>
<% end %>

<% @jobs.each do |job| %>
  <%= link_to job.title, job %>
<% end %>

<% if @jobs.empty? %>
  <p> Nenhuma vaga cadastrada </p>
    <% if current_headhunteruser.present? %>
      <%= link_to 'Cadastrar nova vaga', new_job_path%>  
    <% end %>
<% end %>

app/views/jobs/new.html.erb
<h1> Nova Vaga </h1>

<%= render 'form'%>

app/views/jobs/show.html.erb
<h1><%= "#{@job.title}"%></h1> 

<%= @job.title %>
<%= @job.level %>
<%= @job.description %>
<%= @job.skills %>
<%= number_to_currency @job.salary %>
<%= I18n.l @job.application_deadline, format: :custom %>
<%= @job.location %>

<%= link_to 'Editar', edit_job_path(@job.id) %>
<%= link_to 'Apagar', job_path(@job.id), method: :delete %>
<%= link_to 'Voltar', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HeadHunters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <% if headhunteruser_signed_in? %>  
        <%= link_to 'Vagas Cadastradas', jobs_path %>
        <%= link_to 'Cadastrar Nova Vaga', new_job_path %>
        <%= link_to 'Logout', destroy_headhunteruser_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Acesso HeadHunter', new_headhunteruser_session_path %>
      <% end %>

      <% if applicantuser_signed_in? %>
        <% if applicantuser_signed_in? & current_applicantuser&.applicant.present? %>  
          <%= link_to 'Área do Candidato', applicants_path %>
          <%#= link_to 'Ver Vagas', new_job_path %>
          <%= link_to 'Logout', destroy_applicantuser_session_path, method: :delete %>
        <% else %>
        <%= link_to 'Cadastrar Perfil', new_applicant_path %>
        <%= link_to 'Logout', destroy_applicantuser_session_path, method: :delete %>
        <% end %>
      <% else %>
        <%= link_to 'Acesso Candidato', new_applicantuser_session_path %>
      <% end %>

      <%= link_to 'Home', root_path %>
    </nav>

    <% if flash[:success] %>
      <p><%= flash[:success] %></p>
    <% end %>
    <%= notice %>
    <%= alert %>
    <%= yield %>
  </body>
</html>